
-- add types
INSERT INTO converter.data_type (active, created, updated, created_by, updated_by, translation, name) VALUES (true, now(), now(), -1, -1, false, 'angle');
INSERT INTO converter.data_type (active, created, updated, created_by, updated_by, translation, name) VALUES (true, now(), now(), -1, -1, false, 'fire_rating');
INSERT INTO converter.data_type (active, created, updated, created_by, updated_by, translation, name) VALUES (true, now(), now(), -1, -1, false, 'humidity');
INSERT INTO converter.data_type (active, created, updated, created_by, updated_by, translation, name) VALUES (true, now(), now(), -1, -1, false, 'length');
INSERT INTO converter.data_type (active, created, updated, created_by, updated_by, translation, name) VALUES (true, now(), now(), -1, -1, false, 'ozone');
INSERT INTO converter.data_type (active, created, updated, created_by, updated_by, translation, name) VALUES (true, now(), now(), -1, -1, false, 'percentage');
INSERT INTO converter.data_type (active, created, updated, created_by, updated_by, translation, name) VALUES (true, now(), now(), -1, -1, false, 'power_level');
INSERT INTO converter.data_type (active, created, updated, created_by, updated_by, translation, name) VALUES (true, now(), now(), -1, -1, false, 'pressure');
INSERT INTO converter.data_type (active, created, updated, created_by, updated_by, translation, name) VALUES (true, now(), now(), -1, -1, false, 'electric_conductivity');
INSERT INTO converter.data_type (active, created, updated, created_by, updated_by, translation, name) VALUES (true, now(), now(), -1, -1, false, 'solar_radiation');
INSERT INTO converter.data_type (active, created, updated, created_by, updated_by, translation, name) VALUES (true, now(), now(), -1, -1, false, 'speed');
INSERT INTO converter.data_type (active, created, updated, created_by, updated_by, translation, name) VALUES (true, now(), now(), -1, -1, false, 'temperature');
INSERT INTO converter.data_type (active, created, updated, created_by, updated_by, translation, name) VALUES (true, now(), now(), -1, -1, false, 'uv_index');
INSERT INTO converter.data_type (active, created, updated, created_by, updated_by, translation, name) VALUES (true, now(), now(), -1, -1, false, 'voltage');
INSERT INTO converter.data_type (active, created, updated, created_by, updated_by, translation, name) VALUES (true, now(), now(), -1, -1, false, 'volume');
INSERT INTO converter.data_type (active, created, updated, created_by, updated_by, translation, name) VALUES (true, now(), now(), -1, -1, false, 'mass');
INSERT INTO converter.data_type (active, created, updated, created_by, updated_by, translation, name) VALUES (true, now(), now(), -1, -1, false, 'area');
INSERT INTO converter.data_type (active, created, updated, created_by, updated_by, translation, name) VALUES (true, now(), now(), -1, -1, false, 'energy');
INSERT INTO converter.data_type (active, created, updated, created_by, updated_by, translation, name) VALUES (true, now(), now(), -1, -1, false, 'time');
INSERT INTO converter.data_type (active, created, updated, created_by, updated_by, translation, name) VALUES (true, now(), now(), -1, -1, false, 'electrical_current');
INSERT INTO converter.data_type (active, created, updated, created_by, updated_by, translation, name) VALUES (true, now(), now(), -1, -1, false, 'luminosity');
INSERT INTO converter.data_type (active, created, updated, created_by, updated_by, translation, name) VALUES (true, now(), now(), -1, -1, false, 'frequency');


--Add UOMs
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'mrad','miliradians',converter.get_id_from_data_type(1,'angle'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'°','degrees',converter.get_id_from_data_type(1,'angle'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'rad','radians',converter.get_id_from_data_type(1,'angle'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'grad','gradians',converter.get_id_from_data_type(1,'angle'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'rev','revolutions',converter.get_id_from_data_type(1,'angle'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'','',converter.get_id_from_data_type(1,'fire_rating'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'g/m³','g/m³',converter.get_id_from_data_type(1,'humidity'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'mm','mm',converter.get_id_from_data_type(1,'length'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'cm','cm',converter.get_id_from_data_type(1,'length'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'m','m',converter.get_id_from_data_type(1,'length'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'km','km',converter.get_id_from_data_type(1,'length'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'in','inches',converter.get_id_from_data_type(1,'length'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'ft','foot',converter.get_id_from_data_type(1,'length'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'yd','yards',converter.get_id_from_data_type(1,'length'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'fl','furlong',converter.get_id_from_data_type(1,'length'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'mi','miles',converter.get_id_from_data_type(1,'length'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'nmi','nautical miles',converter.get_id_from_data_type(1,'length'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'DU','Dobson Unit',converter.get_id_from_data_type(1,'ozone'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'%','percent',converter.get_id_from_data_type(1,'percentage'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'?','decimal',converter.get_id_from_data_type(1,'percentage'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'dBm','decibel-milliwatt',converter.get_id_from_data_type(1,'power_level'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'mW','milliwatt',converter.get_id_from_data_type(1,'power_level'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'W','watt',converter.get_id_from_data_type(1,'power_level'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'kW','kilowatt',converter.get_id_from_data_type(1,'power_level'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'MW','megawatt',converter.get_id_from_data_type(1,'power_level'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'Wh','watt hours',converter.get_id_from_data_type(1,'energy'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'kWh','kilo-watt hours',converter.get_id_from_data_type(1,'energy'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'mWh','mega-watt hours',converter.get_id_from_data_type(1,'energy'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'mPa','mili-pascal',converter.get_id_from_data_type(1,'pressure'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'Pa','Pascal',converter.get_id_from_data_type(1,'pressure'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'hPa','hectoPascals',converter.get_id_from_data_type(1,'pressure'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'psi','pounds per square inch',converter.get_id_from_data_type(1,'pressure'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'kPa','kiloPascals',converter.get_id_from_data_type(1,'pressure'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'bar','bar',converter.get_id_from_data_type(1,'pressure'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'dS/m','dS/m',converter.get_id_from_data_type(1,'electric_conductivity'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'mmhos/cm','millimhos/centimetre',converter.get_id_from_data_type(1,'electric_conductivity'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'W/m2','Watts per square metre',converter.get_id_from_data_type(1,'solar_radiation'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'m/h','m/h',converter.get_id_from_data_type(1,'speed'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'km/h','km/h',converter.get_id_from_data_type(1,'speed'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'m/s','m/s',converter.get_id_from_data_type(1,'speed'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'yd/s','yd/s',converter.get_id_from_data_type(1,'speed'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'yd/h','yd/h',converter.get_id_from_data_type(1,'speed'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'mi/h','mi/h',converter.get_id_from_data_type(1,'speed'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'knot','knots',converter.get_id_from_data_type(1,'speed'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'°C','Celsius',converter.get_id_from_data_type(1,'temperature'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'°K','Kelvin',converter.get_id_from_data_type(1,'temperature'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'°F','Fahrenheit',converter.get_id_from_data_type(1,'temperature'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'°Ra','Rankine',converter.get_id_from_data_type(1,'temperature'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'index','index',converter.get_id_from_data_type(1,'uv_index'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'V','volt',converter.get_id_from_data_type(1,'voltage'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'kV','kilovolt',converter.get_id_from_data_type(1,'voltage'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'MV','mega-volt',converter.get_id_from_data_type(1,'voltage'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'ml','ml',converter.get_id_from_data_type(1,'volume'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'cm3','cm^3',converter.get_id_from_data_type(1,'volume'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'L','L',converter.get_id_from_data_type(1,'volume'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'m3','m^3',converter.get_id_from_data_type(1,'volume'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'kL','kilo-liter',converter.get_id_from_data_type(1,'volume'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'ML','mega-liter',converter.get_id_from_data_type(1,'volume'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'tsp','teaspoon',converter.get_id_from_data_type(1,'volume'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'tbsp','tablespoon',converter.get_id_from_data_type(1,'volume'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'fl. oz','fluid ounce',converter.get_id_from_data_type(1,'volume'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'c','cup',converter.get_id_from_data_type(1,'volume'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'pt','pint',converter.get_id_from_data_type(1,'volume'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'qt','quart',converter.get_id_from_data_type(1,'volume'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'gal','gallon',converter.get_id_from_data_type(1,'volume'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'cu in','cubic in',converter.get_id_from_data_type(1,'volume'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'cu ft','cubic foot',converter.get_id_from_data_type(1,'volume'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'mg','mili-gram',converter.get_id_from_data_type(1,'mass'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'gr','gram',converter.get_id_from_data_type(1,'mass'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'kg','kilogram',converter.get_id_from_data_type(1,'mass'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'t','ton',converter.get_id_from_data_type(1,'mass'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'MT','mega-ton',converter.get_id_from_data_type(1,'mass'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'oz','ounce',converter.get_id_from_data_type(1,'mass'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'lb','pound',converter.get_id_from_data_type(1,'mass'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'st','stone',converter.get_id_from_data_type(1,'mass'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'cm^2','square centimetre',converter.get_id_from_data_type(1,'area'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'m^2','square metre',converter.get_id_from_data_type(1,'area'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'km^2','square kilometre',converter.get_id_from_data_type(1,'area'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'ha','hectare',converter.get_id_from_data_type(1,'area'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'sq. in','square inch',converter.get_id_from_data_type(1,'area'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'sq. ft','square foot',converter.get_id_from_data_type(1,'area'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'sq. yd','square yard',converter.get_id_from_data_type(1,'area'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'ac','acre',converter.get_id_from_data_type(1,'area'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'sq. mi','square mile',converter.get_id_from_data_type(1,'area'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'J','joule',converter.get_id_from_data_type(1,'energy'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'kJ','kilo-joule',converter.get_id_from_data_type(1,'energy'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'MJ','mega-joule',converter.get_id_from_data_type(1,'energy'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'GJ','giga-joule',converter.get_id_from_data_type(1,'energy'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'Cal','kilocalorie',converter.get_id_from_data_type(1,'energy'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'mCal','megacalorie?',converter.get_id_from_data_type(1,'energy'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'TJ','tera-joule',converter.get_id_from_data_type(1,'energy'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'sec','seconds',converter.get_id_from_data_type(1,'time'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'min','minutes',converter.get_id_from_data_type(1,'time'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'hrs','hours',converter.get_id_from_data_type(1,'time'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'days','days',converter.get_id_from_data_type(1,'time'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'wks','weeks',converter.get_id_from_data_type(1,'time'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'yrs','years',converter.get_id_from_data_type(1,'time'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'μA','micro-ampere',converter.get_id_from_data_type(1,'electrical_current'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'mA','mili-ampere',converter.get_id_from_data_type(1,'electrical_current'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'A','ampere',converter.get_id_from_data_type(1,'electrical_current'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'kA','kilo-ampere',converter.get_id_from_data_type(1,'electrical_current'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'MA','mega-ampere',converter.get_id_from_data_type(1,'electrical_current'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'cd','candela',converter.get_id_from_data_type(1,'luminosity'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'lm','lumen',converter.get_id_from_data_type(1,'luminosity'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'mHz','milihertz',converter.get_id_from_data_type(1,'frequency'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'Hz','Hertz',converter.get_id_from_data_type(1,'frequency'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'kHz','kilohertz',converter.get_id_from_data_type(1,'frequency'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'MHz','megahertz',converter.get_id_from_data_type(1,'frequency'));
INSERT INTO converter.uom (active, created, updated, created_by, updated_by, owner_user_id, uom_abbreviation, uom_name, data_type_id) VALUES (true, now(), now(), -1, -1,-1,'gHz','gigahertz',converter.get_id_from_data_type(1,'frequency'));

-- Link upper and lower UOMs
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'mm') where uom_name = 'cm';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'm') where uom_name = 'm';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'm') where uom_name = 'km';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'in') where uom_name = 'foot';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'ft') where uom_name = 'yards';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'yd') where uom_name = 'miles';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'mW') where uom_name = 'watt';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'W') where uom_name = 'kilowatt';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'kW') where uom_name = 'megawatt';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'Wh') where uom_name = 'kilo-watt hours';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'kWh') where uom_name = 'mega-watt hours';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'mPa') where uom_name = 'Pascal';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'Pa') where uom_name = 'hectoPascals';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'hPa') where uom_name = 'kiloPascals';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'cm/h') where uom_name = 'm/h';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'm/h') where uom_name = 'km/h';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'ft/h') where uom_name = 'yd/h';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'yd/h') where uom_name = 'mi/h';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'dV') where uom_name = 'volt';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'hV') where uom_name = 'kilovolt';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'kV') where uom_name = 'mega-volt';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'ml') where uom_name = 'L';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'cm3') where uom_name = 'm^3';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'L') where uom_name = 'kilo-liter';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'kL') where uom_name = 'mega-liter';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'tsp') where uom_name = 'tablespoon';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'tbsp') where uom_name = 'fluid ounce';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'fl. oz') where uom_name = 'cup';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'c') where uom_name = 'pint';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'pt') where uom_name = 'quart';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'qt') where uom_name = 'gallon';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'cu in') where uom_name = 'cubic foot';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'mg') where uom_name = 'gram';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'gr') where uom_name = 'kilogram';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'kg') where uom_name = 'ton';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 't') where uom_name = 'mega-ton';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'oz') where uom_name = 'pound';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'lb') where uom_name = 'stone';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'cm2') where uom_name = 'square metre';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'm2') where uom_name = 'square kilometre';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'km2') where uom_name = 'hectare';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'sq. in') where uom_name = 'square foot';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'sq. ft') where uom_name = 'square yard';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'sq. yd') where uom_name = 'acre';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'ac') where uom_name = 'square mile';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'kJ') where uom_name = 'joule';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'J') where uom_name = 'kilo-joule';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'kJ') where uom_name = 'mega-joule';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'MJ') where uom_name = 'giga-joule';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'GJ') where uom_name = 'tera-joule';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'sec') where uom_name = 'minutes';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'min') where uom_name = 'hours';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'hrs') where uom_name = 'days';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'days') where uom_name = 'weeks';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'wks') where uom_name = 'years';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'μA') where uom_name = 'mili-ampere';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'mA') where uom_name = 'ampere';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'A') where uom_name = 'kilo-ampere';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'kA') where uom_name = 'mega-ampere';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'mHz') where uom_name = 'Hertz';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'Hz') where uom_name = 'kilohertz';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'kHz') where uom_name = 'megahertz';
UPDATE converter.uom set lower_uom = (select id from converter.uom where uom_abbreviation  = 'MHz') where uom_name = 'gigahertz';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'cm') where uom_name = 'mm';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'm') where uom_name = 'cm';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'km') where uom_name = 'm';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'ft') where uom_name = 'inches';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'yd') where uom_name = 'foot';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'mi') where uom_name = 'yards';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'W') where uom_name = 'milliwatt';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'kW') where uom_name = 'watt';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'MW') where uom_name = 'kilowatt';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'kWh') where uom_name = 'watt hours';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'mWh') where uom_name = 'kilo-watt hours';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'Pa') where uom_name = 'mili-pascal';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'hPa') where uom_name = 'Pascal';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'kPa') where uom_name = 'hectoPascals';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'km/h') where uom_name = 'm/h';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'mi/h') where uom_name = 'yd/h';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'DV') where uom_name = 'volt';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'MV') where uom_name = 'kilovolt';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'L') where uom_name = 'ml';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'm3') where uom_name = 'cm^3';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'kL') where uom_name = 'L';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'ML') where uom_name = 'kilo-liter';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'tbsp') where uom_name = 'teaspoon';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'fl. oz') where uom_name = 'tablespoon';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'c') where uom_name = 'fluid ounce';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'pt') where uom_name = 'cup';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'qt') where uom_name = 'pint';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'gal') where uom_name = 'quart';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'cu ft') where uom_name = 'cubic in';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'gr') where uom_name = 'mili-gram';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'kg') where uom_name = 'gram';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 't') where uom_name = 'kilogram';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'MT') where uom_name = 'ton';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'lb') where uom_name = 'ounce';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'st') where uom_name = 'pound';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'm2') where uom_name = 'square centimetre';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'km2') where uom_name = 'square metre';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'ha') where uom_name = 'square kilometre';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'sq. ft') where uom_name = 'square inch';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'sq. yd') where uom_name = 'square foot';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'ac') where uom_name = 'square yard';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'sq. mi') where uom_name = 'acre';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'kJ') where uom_name = 'joule';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'MJ') where uom_name = 'kilo-joule';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'GJ') where uom_name = 'mega-joule';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'TJ') where uom_name = 'giga-joule';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'min') where uom_name = 'seconds';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'hrs') where uom_name = 'minutes';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'days') where uom_name = 'hours';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'wks') where uom_name = 'days';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'yrs') where uom_name = 'weeks';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'mA') where uom_name = 'micro-ampere';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'A') where uom_name = 'mili-ampere';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'kA') where uom_name = 'ampere';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'MA') where uom_name = 'kilo-ampere';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'Hz') where uom_name = 'milihertz';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'kHz') where uom_name = 'Hertz';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'MHz') where uom_name = 'kilohertz';
UPDATE converter.uom set upper_uom = (select id from converter.uom where uom_abbreviation = 'gHz') where uom_name = 'megahertz';
